---
deployment:
  tasks:
    # Deploy static files to public_html
    - export DEPLOYPATH=/home/bitcoinbagger/public_html/

    # Create necessary directories
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/mkdir -p $DEPLOYPATH/api/cache
    - /bin/mkdir -p $DEPLOYPATH/public
    - /bin/mkdir -p $DEPLOYPATH/public/js

    # Copy main HTML files (now in root directory)
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp companies.html $DEPLOYPATH
    - /bin/cp etfs.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    
    # Copy API files
    - /bin/cp api/treasuries.php $DEPLOYPATH/api/
    - /bin/cp api/etf-holdings.php $DEPLOYPATH/api/
    - /bin/cp api/btc-price.php $DEPLOYPATH/api/
    
    # Copy JavaScript files
    - /bin/cp public/js/*.js $DEPLOYPATH/public/js/
    
    # Copy documentation
    - /bin/cp -r docs $DEPLOYPATH/ 2>/dev/null || true
    
    # Set proper permissions for PHP files
    - /bin/chmod 644 $DEPLOYPATH/*.html
    - /bin/chmod 644 $DEPLOYPATH/*.css
    - /bin/chmod 644 $DEPLOYPATH/api/*.php
    - /bin/chmod 644 $DEPLOYPATH/public/js/*.js
    
    # Set cache directory permissions
    - /bin/chmod 755 $DEPLOYPATH/api/cache
    - /bin/chmod 666 $DEPLOYPATH/api/cache/* 2>/dev/null || true
    
    # Create .htaccess for API routing and caching
    - |
      cat > $DEPLOYPATH/.htaccess << 'EOF'
      # BitcoinBagger - Static Site with PHP APIs
      
      # Enable compression
      <IfModule mod_deflate.c>
          AddOutputFilterByType DEFLATE text/plain
          AddOutputFilterByType DEFLATE text/html
          AddOutputFilterByType DEFLATE text/xml
          AddOutputFilterByType DEFLATE text/css
          AddOutputFilterByType DEFLATE application/xml
          AddOutputFilterByType DEFLATE application/xhtml+xml
          AddOutputFilterByType DEFLATE application/rss+xml
          AddOutputFilterByType DEFLATE application/javascript
          AddOutputFilterByType DEFLATE application/x-javascript
          AddOutputFilterByType DEFLATE application/json
      </IfModule>
      
      # Cache static assets
      <IfModule mod_expires.c>
          ExpiresActive on
          ExpiresByType text/css "access plus 1 month"
          ExpiresByType application/javascript "access plus 1 month"
          ExpiresByType text/javascript "access plus 1 month"
          ExpiresByType image/png "access plus 1 month"
          ExpiresByType image/jpg "access plus 1 month"
          ExpiresByType image/jpeg "access plus 1 month"
          ExpiresByType image/gif "access plus 1 month"
          ExpiresByType image/svg+xml "access plus 1 month"
      </IfModule>
      
      # API CORS headers
      <IfModule mod_headers.c>
          <FilesMatch "\.(php)$">
              Header set Access-Control-Allow-Origin "*"
              Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"
              Header set Access-Control-Allow-Headers "Content-Type"
          </FilesMatch>
      </IfModule>
      
      # Security headers
      Header always set X-Content-Type-Options nosniff
      Header always set X-Frame-Options DENY
      Header always set X-XSS-Protection "1; mode=block"
      
      # Default document
      DirectoryIndex index.html
      
      # Error pages
      ErrorDocument 404 /index.html
      EOF
    
    # Create environment file for API keys (you'll need to add your keys)
    - |
      cat > $DEPLOYPATH/api/.env << 'EOF'
      # BitcoinBagger API Configuration
      # Add your API keys here after deployment
      
      # CoinGecko API (Primary)
      COINGECKO_API_KEY=your_coingecko_key_here
      
      # Financial Modeling Prep (Fallback)
      FMP_API_KEY=your_fmp_key_here
      
      # Alpha Vantage (Fallback)
      ALPHA_VANTAGE_API_KEY=your_alpha_vantage_key_here
      
      # TwelveData (Fallback)
      TWELVEDATA_API_KEY=your_twelvedata_key_here
      
      # Cache settings
      CACHE_DURATION_COMPANIES=86400
      CACHE_DURATION_PRICE=60
      CACHE_DURATION_ETFS=86400
      EOF
    
    # Set environment file permissions
    - /bin/chmod 600 $DEPLOYPATH/api/.env
    
    # Create deployment log
    - echo "BitcoinBagger V4 deployed successfully at $(date)" >> $DEPLOYPATH/deployment.log
    - echo "Commit: $(git rev-parse HEAD)" >> $DEPLOYPATH/deployment.log
    - echo "Branch: $(git branch --show-current)" >> $DEPLOYPATH/deployment.log
