---
deployment:
  tasks:
    # Deploy all files to public_html
    - export DEPLOYPATH=/home/bitcoinbagger/public_html/
    
    # Copy main files
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R companies.html $DEPLOYPATH
    - /bin/cp -R etfs.html $DEPLOYPATH
    - /bin/cp -R styles.css $DEPLOYPATH
    - /bin/cp -R README.md $DEPLOYPATH
    
    # Copy directories
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    
    # Set proper permissions for PHP files
    - /bin/chmod 644 $DEPLOYPATH/api/*.php
    - /bin/chmod 755 $DEPLOYPATH/api/cache
    
    # Ensure cache directory exists and is writable
    - /bin/mkdir -p $DEPLOYPATH/api/cache
    - /bin/chmod 755 $DEPLOYPATH/api/cache
    
    # Set permissions for HTML and CSS files
    - /bin/chmod 644 $DEPLOYPATH/*.html
    - /bin/chmod 644 $DEPLOYPATH/*.css
    - /bin/chmod 644 $DEPLOYPATH/public/js/*.js
    
    # Exclude .env from deployment (keep server version)
    # This prevents overwriting API keys on deployment
